### PR TITLE
Bugfixes and translations

### PR DESCRIPTION
**Pull request by ImperatorS79**
Hello.

I reworked some of the french translations, and fixed a bug where the number of soldier was not displayed.

Despite the level when you are playing a game with Otello, which does not work (the troops does not spawn at the right place) in 1.14, this add-on seems to work quite well.

May I maybe upload it on the 1.14 add-ons server, and asking other contributors for help if you do not have time to check this ?

### CODE REVIEW

**Comment by trewe** [comment]
this campaign hasn't been updated in a long time, mainly indeed for lack of time...

> Hello.
> 
> I reworked some of the french translations, and fixed a bug where the number of soldier was not displayed.

since the included translations are ancient regenerating the po files will make this pr most likely obsolete. Better to wait until the porting process is over, before beginning with the translations.

> 
> Despite the level when you are playing a game with Otello, which does not work (the troops does not spawn at the right place) in 1.14, this add-on seems to work quite well.
> 

Considering the last working version is for 1.12 that's seems impressive.

> May I maybe upload it on the 1.14 add-ons server, and asking other contributors for help if you do not have time to check this ?

If you are ready to take the maintenance of the campaign, ok.

**Comment by ImperatorS79** [comment]
> since the included translations are ancient regenerating the po files will make this pr most likely obsolete. Better to wait until the porting process is over, before beginning with the translations.

Well I regenerated the .pot from the source file before updating the translation.

> If you are ready to take the maintenance of the campaign, ok.

Well, I was more thinking of "Hey look this campaign still exist" than maintaining it myself, like I have seen for some add-ons on the add-ons server ^^.

**Comment by trewe** [comment]
> Well, I was more thinking of "Hey look this campaign still exist" than maintaining it myself, like I have seen for some add-ons on the add-ons server ^^.

biggest burden of this campaign is the insane amount of legacy code present (some dating back to 1.4) and the general messy nature of the wml since it dates back when I was a beginner with the syntax.

Fixing the othello map was trivial (only an uninitialized variable), which together with this PR may pass as "good enough".

**Comment by trewe** [comment]
still interested in mainternership?

**Comment by ImperatorS79** [comment]
I will recall what I have said earlier:

> Well, I was more thinking of "Hey look this campaign still exist" than maintaining it myself, like I have seen for some add-ons on the add-ons server ^^.

^^

**Pull request merged**
